name: CD

on:
  push:
    tags:
    - '*'

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Build
      run: dotnet pack --configuration Release
    
    - name: Upload to NuGet
      run: dotnet nuget push SByteDev.Serilog.Sinks.AppCenter/bin/Release/*.nupkg --source nuget.org --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
