name: CD

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SOLUTION_DIR: ./SByteDev.Serilog.Sinks.AppCenter
      PROJECT_DIR: SByteDev.Serilog.Sinks.AppCenter

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup
      uses: actions/setup-dotnet@v1.4.0
    - name: Pack
      working-directory: ${{ env.SOLUTION_DIR }}
      run: dotnet pack --configuration Release
    - name: Push to NuGet
      working-directory: ${{ env.SOLUTION_DIR }}
      run: dotnet nuget push ${{ env.PROJECT_DIR }}/bin/Release/*.nupkg --source nuget.org --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
