name: CD

on:
  create:
    tags:
      - '*'

jobs:
  build:
    
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup
      uses: actions/setup-dotnet@v1.4.0
    - name: Pack
      working-directory: ./SByteDev.Serilog.Sinks.AppCenter
      run: dotnet pack --configuration Release
    - name: Setup NuGet config
      run: sed 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' .nuget.config > nuget.config
    - name: GitHub Package Registry Push
      run: nuget push /**/*.nupkg -Source "github" -SkipDuplicate
    - name: NuGet Push
      run: nuget push /**/*.nupkg -Source "nuget" -ApiKey ${{ secrets.NUGET_API_KEY }} -SkipDuplicate
