name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SOLUTION_DIR: ./SByteDev.Serilog.Sinks.AppCenter

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup
      uses: actions/setup-dotnet@v1.4.0
    - name: Test
      working-directory: ${{ env.SOLUTION_DIR }}
      run: dotnet build
